services:
  - type: web
    name: clinicaltrial-match
    runtime: docker
    dockerfilePath: ./docker/Dockerfile
    dockerContext: .
    plan: free
    healthCheckPath: /v1/health
    envVars:
      - key: MARTIAN_API_KEY
        value: sk-42472a65551a48fd8face8ea27ef371f
      - key: CTM_DB__PATH
        value: /tmp/clinicaltrial_match.db
      - key: CTM_API__HOST
        value: 0.0.0.0
      - key: CTM_API__PORT
        value: "8000"
      - key: PORT
        value: "8000"
